name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    timeout-minutes: 2
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies (client)
        run: npm ci
        working-directory: ./client
      - name: Install dependencies (client)
        run: npm ci
        working-directory: ./server
      - run: npm test
        env:
          ATLAS_URL: ${{ secrets.ATLAS_URL }}
      - name: Coverage (client)
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./client/coverage/lcov.info
      - name: Coverage (server)
        uses: romeovs/lcov-reporter-action@v0.2.16
        with:
          lcov-file: ./server/coverage/lcov.info
      - uses: tanmen/jest-reporter@v1
        if: always()
        with:
          result-file: ./client/jest-report.json
          github-token: ${{ secrets.GITHUB_TOKEN }}
